import fs from 'node:fs';
import path from 'node:path';

const descriptions = {
  'data/people': 'Canonical person records focused on documented corpus contributions.',
  'data/organization-references': 'Minimal, versioned references to CXO Ecosystem Index organization identities.',
  'data/book-works': 'Underlying book works, independent of any edition.',
  'data/book-editions': 'Edition-specific bibliographic and lawful-access records.',
  'data/sources': 'Canonical media, publication, research, and OFF source identities.',
  'data/statements': 'Attributed, source-located, neutral source statements.',
  'data/propositions': 'Neutral normalized propositions linked to statements.',
  'data/stances': 'Explicit statement-to-proposition stance relationships.',
  'data/topics': 'Reviewed controlled-topic records; new topics begin in staging.',
  'data/roles': 'Controlled executive-role records and aliases.',
  'data/geographies': 'Controlled geography records that preserve geographic context types.',
  'data/languages': 'Controlled language records using stable identifiers.',
  'data/debates': 'Evidence-bounded debate maps with comparable scopes.',
  'data/dossiers': 'Editorial syntheses with explicit evidence lineage.',
  'data/trends': 'Frozen-corpus trend snapshots with disclosed denominators.',
  'data/protocols': 'Pre-registered research protocols.',
  'data/batches': 'Completed canonical batch manifests after review.',
  'data/reviews': 'Review decisions and disagreements.',
  'data/corrections': 'Correction records preserving prior and revised values.',
  'data/releases': 'Approved semantic releases and checksums.',
  'data/aliases': 'Alias maps and retired IDs. Canonical IDs are never reassigned.',
  'data/external/cxo-ecosystem-index': 'Pinned local fallback manifest for the CXO Ecosystem Index crosswalk.',
  'data/external/executive-ai-research': 'Pinned local fallback manifest for Executive AI Research references.',
  'content/people': 'Long-form editorial material for eligible person pages; facts come from data records.',
  'content/books': 'Original book analysis only; bibliographic facts come from data records.',
  'content/sources': 'Source analysis that adds value beyond linking.',
  'content/topic-dossiers': 'Human-reviewed long-form topic synthesis.',
  'content/debate-maps': 'Human-reviewed explanatory text for debate maps.',
  'content/role-briefings': 'Evidence-qualified executive-role comparisons.',
  'content/regional-briefings': 'Region-specific synthesis with geographic distinctions.',
  'content/executive-signal': 'Narrative context for frozen-corpus trend snapshots.',
  'content/methodology-explainers': 'Plain-language explanations of public methods.',
  'staging/batches': 'One documented research batch per branch; never published.',
  'staging/proposed-taxonomy': 'Taxonomy additions awaiting review; never published.',
  'staging/duplicate-review': 'Potential identity and prose duplicates awaiting decisions.',
  'staging/identity-review': 'Ambiguous people, works, sources, and organizations.',
  'staging/rights-review': 'Unresolved licenses, permissions, and quotation questions.',
  'staging/translation-review': 'Translated metadata and paraphrases awaiting language review.',
  'staging/statement-review': 'Statement extraction candidates awaiting attribution review.',
  'staging/proposition-review': 'Proposition candidates awaiting scope and evidence review.',
  'staging/rejected': 'Rejected-source logs with reasons; source text is not stored.',
  'migrations/versions': 'Versioned, reversible schema and data migration programs.',
  'operations/prompts/versions': 'Immutable prompt versions referenced by research batches.',
  'operations/research-batch-template': 'Documented batch templates used by the scaffolding command.',
  'operations/review-checklists': 'Attribution, rights, privacy, and publication checklists.',
  'operations/release-checklist': 'Release approval and deployment checks.',
  'operations/coverage-dashboard': 'Generated corpus coverage, concentration, and duplicate audits.',
  'review-tools/generated': 'Local-only generated review packet indexes; excluded from Pages.',
  'review-tools/local-review-interface': 'Local review interface documentation and future UI assets.',
  'tests/fixtures/synthetic': 'Obviously fictional reserved fixtures covering every major entity.',
  'tests/fixtures/invalid': 'Purpose-built invalid fixtures that prove validation failures.',
  'tests/fixtures/gold-review': 'Expected review decisions for repeatable quality checks.',
  'tests/schema': 'Schema contract tests.',
  'tests/provenance': 'Provenance rule tests.',
  'tests/attribution': 'Attribution and locator tests.',
  'tests/copyright': 'Rights boundary tests.',
  'tests/privacy': 'Privacy and confidentiality tests.',
  'tests/links': 'Internal and canonical link tests.',
  'tests/structured-data': 'Structured-data contract tests.',
  'tests/publication-gates': 'Workflow and human-approval gate tests.',
  'tests/search': 'Static search and exclusion tests.',
  'tests/accessibility': 'Keyboard, landmark, label, and reduced-motion checks.',
  'tests/content-quality': 'Near-duplicate and prohibited-language checks.'
};

for (const [directory, description] of Object.entries(descriptions)) {
  const target = path.join(process.cwd(), directory);
  fs.mkdirSync(target, { recursive: true });
  const title = directory.split('/').at(-1).replaceAll('-', ' ');
  fs.writeFileSync(path.join(target, 'README.md'), `# ${title[0].toUpperCase()}${title.slice(1)}\n\n${description}\n`);
}
